interface Env{SUPABASE_URL:string;SUPABASE_SECRET_KEY?:string;SUPABASE_SERVICE_ROLE_KEY?:string;SESSION_SECRET:string;APP_ORIGIN:string;COOKIE_SECURE?:string;BOOTSTRAP_TOKEN?:string}
type Ctx={env:Env,user?:any,session?:any,csrf?:string};
const json=(body:unknown,status=200,headers:HeadersInit={})=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const err=(message:string,status=400)=>json({error:message},status);
const b64=(a:ArrayBuffer)=>btoa(String.fromCharCode(...new Uint8Array(a))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const random=(n=32)=>{const a=new Uint8Array(n);crypto.getRandomValues(a);return b64(a.buffer)};
async function digest(s:string){return b64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))}
async function passwordHash(password:string,salt=random(16),iterations=100000){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:new TextEncoder().encode(salt),iterations},key,256);return `pbkdf2_sha256$${iterations}$${salt}$${b64(bits)}`}
async function passwordOK(password:string,encoded:string){const [alg,it,salt]=encoded.split('$');if(alg!=='pbkdf2_sha256')return false;const actual=await passwordHash(password,salt,Number(it));const a=new TextEncoder().encode(actual),b=new TextEncoder().encode(encoded);if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a[i]^b[i];return diff===0}
class DbError extends Error{constructor(public status:number,public code:string,public detail:string){super(`supabase_${status}_${code}`)}}
async function db(ctx:Ctx,path:string,init:RequestInit={}){const key=ctx.env.SUPABASE_SERVICE_ROLE_KEY||ctx.env.SUPABASE_SECRET_KEY;if(!ctx.env.SUPABASE_URL)throw new DbError(0,'missing_url','');if(!key)throw new DbError(0,'missing_key','');const h=new Headers(init.headers);h.set('apikey',key);if(key.startsWith('eyJ'))h.set('Authorization','Bearer '+key);h.set('Content-Type','application/json');h.set('Prefer',h.get('Prefer')||'return=representation');const base=ctx.env.SUPABASE_URL.replace(/\/+$/,'');const r=await fetch(base+'/rest/v1/'+path,{...init,headers:h});const text=await r.text();if(!r.ok){let parsed:any={};try{parsed=JSON.parse(text)}catch{}throw new DbError(r.status,String(parsed.code||'http_error'),String(parsed.message||text).slice(0,300))}return text?JSON.parse(text):null}
const q=(s:string)=>encodeURIComponent(s);
function cookie(req:Request,name:string){return req.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1)}
function setCookie(ctx:Ctx,token:string,maxAge=8*3600){return `pt_session=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${maxAge}${ctx.env.COOKIE_SECURE==='false'?'':'; Secure'}`}
async function body(req:Request){try{return await req.json() as any}catch{return{}}}
async function audit(ctx:Ctx,action:string,entity:string,entityId?:string,oldValue?:unknown,newValue?:unknown,note?:string){await db(ctx,'audit_log',{method:'POST',body:JSON.stringify({user_id:ctx.user?.id,action,entity,entity_id:entityId,old_value:oldValue,new_value:newValue,note})})}
async function auth(ctx:Ctx,req:Request){const token=cookie(req,'pt_session');if(!token)return false;const hash=await digest(token);const rows=await db(ctx,`sessions?token_hash=eq.${q(hash)}&revoked_at=is.null&expires_at=gt.${q(new Date().toISOString())}&select=*,users(*)`);if(!rows?.[0]?.users?.active)return false;ctx.session=rows[0];ctx.user=rows[0].users;ctx.csrf=rows[0].csrf_token;return true}
function allow(ctx:Ctx,role?:string){return !!ctx.user&&(!role||ctx.user.role===role)}
function csrfOK(ctx:Ctx,req:Request){return ['GET','HEAD'].includes(req.method)||req.headers.get('X-CSRF-Token')===ctx.csrf}
const cleanUser=(u:any)=>({id:u.id,full_name:u.full_name,username:u.username,role:u.role,usual_kiosk_id:u.usual_kiosk_id,active:u.active,last_login_at:u.last_login_at,created_at:u.created_at});

export const onRequest:PagesFunction<Env>=async({request,env,params})=>{
 const ctx:Ctx={env};const rawPath=params.path;const parts=(Array.isArray(rawPath)?rawPath.map(String):String(rawPath||'').split('/')).filter(Boolean);const route='/'+parts.join('/');
 try{
  if(request.method==='OPTIONS')return new Response(null,{status:204});
  if(route==='/version'&&request.method==='GET')return json({version:'1.2.0',routing:'array-safe',database_errors:'detailed'});
  if(route==='/bootstrap'&&request.method==='POST'){
    if(!env.BOOTSTRAP_TOKEN||request.headers.get('X-Bootstrap-Token')!==env.BOOTSTRAP_TOKEN)return err('Configuração inicial não autorizada.',403);
    const existing=await db(ctx,'users?select=id&limit=1');if(existing.length)return err('A configuração inicial já foi concluída.',409);
    const b=await body(request);if(!b.username||!b.full_name||String(b.password||'').length<6)return err('Preencha o nome, utilizador e uma palavra-passe com pelo menos 6 caracteres.');
    await db(ctx,'users',{method:'POST',body:JSON.stringify({full_name:b.full_name,username:String(b.username).toLowerCase(),password_hash:await passwordHash(b.password),role:'admin'})});return json({ok:true});
  }
  if(route==='/auth/login'&&request.method==='POST'){
    const b=await body(request),username=String(b.username||'').trim().toLowerCase(),ip=request.headers.get('CF-Connecting-IP')||'local',key=await digest(ip+':'+username),since=new Date(Date.now()-15*60000).toISOString();
    const attempts=await db(ctx,`login_attempts?attempt_key=eq.${q(key)}&created_at=gt.${q(since)}&success=eq.false&select=id`);if(attempts.length>=5)return err('Demasiadas tentativas. Aguarde 15 minutos.',429);
    const users=await db(ctx,`users?username=eq.${q(username)}&select=*`),u=users[0];const ok=!!u&&u.active&&await passwordOK(String(b.password||''),u.password_hash);
    await db(ctx,'login_attempts',{method:'POST',body:JSON.stringify({attempt_key:key,success:ok})});if(!ok)return err('Nome de utilizador ou palavra-passe incorretos.',401);
    const token=random(),csrfToken=random(24),tokenHash=await digest(token);await db(ctx,'sessions',{method:'POST',body:JSON.stringify({user_id:u.id,token_hash:tokenHash,csrf_token:csrfToken,expires_at:new Date(Date.now()+8*3600000).toISOString()})});await db(ctx,`users?id=eq.${u.id}`,{method:'PATCH',body:JSON.stringify({last_login_at:new Date().toISOString()})});return json({user:cleanUser(u),csrf:csrfToken},200,{'Set-Cookie':setCookie(ctx,token)});
  }
  if(!await auth(ctx,request))return err('A sessão terminou. Volte a iniciar sessão.',401);if(!csrfOK(ctx,request))return err('Pedido inválido. Atualize a página e tente novamente.',403);
  if(route==='/auth/me'&&request.method==='GET')return json({user:cleanUser(ctx.user),csrf:ctx.csrf});
  if(route==='/auth/logout'&&request.method==='POST'){await db(ctx,`sessions?id=eq.${ctx.session.id}`,{method:'PATCH',body:JSON.stringify({revoked_at:new Date().toISOString()})});return json({ok:true},200,{'Set-Cookie':setCookie(ctx,'',0)});}
  if(route==='/auth/change-password'&&request.method==='POST'){const b=await body(request);if(!await passwordOK(String(b.current_password||''),ctx.user.password_hash))return err('A palavra-passe atual está incorreta.',400);if(String(b.password||'').length<6)return err('A nova palavra-passe deve ter pelo menos 6 caracteres.');await db(ctx,`users?id=eq.${ctx.user.id}`,{method:'PATCH',body:JSON.stringify({password_hash:await passwordHash(b.password)})});await db(ctx,`sessions?user_id=eq.${ctx.user.id}&id=neq.${ctx.session.id}`,{method:'PATCH',body:JSON.stringify({revoked_at:new Date().toISOString()})});await audit(ctx,'alterar palavra-passe','utilizador',ctx.user.id);return json({ok:true})}
  if(route==='/dashboard'&&request.method==='GET'){const own=ctx.user.role==='admin'?'':`&started_by=eq.${q(ctx.user.id)}`;const returnOwner=ctx.user.role==='admin'?'':`&rentals.started_by=eq.${q(ctx.user.id)}`;const [bikes,kiosks,rentals,faults,returns]=await Promise.all([db(ctx,'bikes?active=eq.true&select=id,code,status,kiosk_id'),db(ctx,'kiosks?active=eq.true&select=*'),db(ctx,`rentals?status=eq.Em%20aberto${own}&select=id`),db(ctx,'faults?status=in.(Aberta,Em%20análise,Em%20reparação)&select=*,bikes(code)&order=created_at.desc&limit=8'),db(ctx,`rental_items?returned_at=not.is.null${returnOwner}&select=id,returned_at,rentals!inner(customer_ref,started_by),bikes(code)&order=returned_at.desc&limit=8`)]);const counts:any={},counts_by_type:any={};bikes.forEach((b:any)=>{counts[b.status]=(counts[b.status]||0)+1;const row=counts_by_type[b.status]||(counts_by_type[b.status]={total:0,electric:0,conventional:0});row.total++;if(String(b.code||'').startsWith('E'))row.electric++;else if(String(b.code||'').startsWith('C'))row.conventional++});const rentedBikes=bikes.filter((b:any)=>b.status==='Alugada'),rented={total:rentedBikes.length,electric:rentedBikes.filter((b:any)=>String(b.code||'').startsWith('E')).length,conventional:rentedBikes.filter((b:any)=>String(b.code||'').startsWith('C')).length,by_kiosk:kiosks.map((k:any)=>{const list=rentedBikes.filter((b:any)=>b.kiosk_id===k.id);return{id:k.id,name:k.name,total:list.length,electric:list.filter((b:any)=>String(b.code||'').startsWith('E')).length,conventional:list.filter((b:any)=>String(b.code||'').startsWith('C')).length}})};return json({counts,counts_by_type,rented,kiosks:kiosks.map((k:any)=>({...k,total:bikes.filter((b:any)=>b.kiosk_id===k.id).length})),open_rentals:rentals.length,pending_faults:faults.length,faults:faults.map((f:any)=>({...f,bike_code:f.bikes?.code})),recent_returns:returns.map((r:any)=>({...r,bike_code:r.bikes?.code,customer_ref:r.rentals?.customer_ref}))})}
  if(route==='/bikes'&&request.method==='GET'){const [bikes,kiosks]=await Promise.all([db(ctx,'bikes?select=*,kiosk:kiosks(*)&order=code'),db(ctx,'kiosks?active=eq.true&select=*&order=name')]);return json({bikes,kiosks})}
  if(route==='/bikes'&&request.method==='POST'){if(!allow(ctx,'admin'))return err('Apenas administradores podem criar bicicletas.',403);const b=await body(request),type=b.type==='E'?'E':'C',number=String(b.number||b.code||'').replace(/^[EC]/i,'');if(!/^\d{1,6}$/.test(number))return err('Indique um número válido para a bicicleta.');const code=type+number.padStart(3,'0');const rows=await db(ctx,'bikes',{method:'POST',body:JSON.stringify({code,model:b.model||(type==='E'?'Bicicleta elétrica':'Bicicleta convencional'),kiosk_id:b.kiosk_id,status:'Disponível'})});await audit(ctx,'criar','bicicleta',rows[0].id,null,rows[0]);return json(rows[0],201)}
  if(parts[0]==='bikes'&&parts[1]&&parts[2]==='history'&&request.method==='GET'){if(!allow(ctx,'admin'))return err('Acesso reservado a administradores.',403);const [bike,items,faults]=await Promise.all([db(ctx,`bikes?id=eq.${parts[1]}&select=*,kiosk:kiosks(*)`),db(ctx,`rental_items?bike_id=eq.${parts[1]}&select=*,return_kiosk:kiosks(*),returned_by_user:users!rental_items_returned_by_fkey(full_name),rental:rentals(*,start_kiosk:kiosks(*),started_by_user:users!rentals_started_by_fkey(full_name),returned_by_user:users!rentals_returned_by_fkey(full_name))&order=returned_at.desc.nullsfirst`),db(ctx,`faults?bike_id=eq.${parts[1]}&select=*,created_by_user:users!faults_created_by_fkey(full_name),interventions:maintenance_interventions(*,created_by_user:users!maintenance_interventions_created_by_fkey(full_name))&order=created_at.desc`)]);if(!bike[0])return err('Bicicleta não encontrada.',404);return json({bike:bike[0],rental_items:items,faults})}
  if(parts[0]==='bikes'&&parts[1]&&request.method==='PATCH'){if(!allow(ctx,'admin'))return err('Apenas administradores podem alterar bicicletas.',403);const old=(await db(ctx,`bikes?id=eq.${parts[1]}&select=*`))[0];if(!old)return err('Bicicleta não encontrada.',404);const b=await body(request),allowed=['model','kiosk_id','status','notes','active','photo_url'];const update=Object.fromEntries(Object.entries(b).filter(([k])=>allowed.includes(k)));const rows=await db(ctx,`bikes?id=eq.${parts[1]}`,{method:'PATCH',body:JSON.stringify(update)});await audit(ctx,'alterar','bicicleta',parts[1],old,rows[0],b.justification);return json(rows[0])}
  if(route==='/rentals'&&request.method==='GET'){const owner=ctx.user.role==='admin'?'':`&started_by=eq.${q(ctx.user.id)}`;const [rentals,bikes,kiosks]=await Promise.all([db(ctx,`rentals?select=*,start_kiosk:kiosks(*),started_by_user:users!rentals_started_by_fkey(full_name),returned_by_user:users!rentals_returned_by_fkey(full_name),items:rental_items(*,bike:bikes(*),return_kiosk:kiosks(*),returned_by_user:users!rental_items_returned_by_fkey(full_name))${owner}&order=started_at.desc&limit=500`),db(ctx,'bikes?active=eq.true&status=eq.Disponível&select=*,kiosk:kiosks(*)&order=code'),db(ctx,'kiosks?active=eq.true&allows_rentals=eq.true&select=*&order=name')]);return json({rentals,available_bikes:bikes,kiosks})}
  if(route==='/rentals'&&request.method==='POST'){const b=await body(request);if(!b.customer_ref?.trim()||!Array.isArray(b.bike_ids)||!b.bike_ids.length)return err('Indique o cliente e pelo menos uma bicicleta.');const rows=await db(ctx,'rpc/start_rental',{method:'POST',body:JSON.stringify({p_customer_ref:b.customer_ref.trim(),p_start_kiosk_id:b.start_kiosk_id,p_bike_ids:b.bike_ids,p_user_id:ctx.user.id})});return json(rows,201)}
  if(parts[0]==='rentals'&&parts[2]==='return'&&request.method==='POST'){const rental=(await db(ctx,`rentals?id=eq.${parts[1]}&select=id,started_by,start_kiosk_id`))[0];if(!rental)return err('Aluguer não encontrado.',404);if(ctx.user.role!=='admin'&&rental.started_by!==ctx.user.id)return err('Não pode alterar alugueres de outro utilizador.',403);const b=await body(request);if(!b.items?.length)return err('Não existem bicicletas por devolver.');const result=await db(ctx,'rpc/return_rental_items',{method:'POST',body:JSON.stringify({p_rental_id:parts[1],p_return_kiosk_id:b.return_kiosk_id||ctx.user.usual_kiosk_id||rental.start_kiosk_id,p_items:b.items,p_user_id:ctx.user.id})});return json(result)}
  if(route==='/faults'&&request.method==='GET'){const [faults,bikes]=await Promise.all([db(ctx,'faults?select=*,bike:bikes(*),created_by_user:users!faults_created_by_fkey(full_name)&order=created_at.desc&limit=1000'),db(ctx,'bikes?active=eq.true&select=*&order=code')]);return json({faults,bikes})}
  if(route==='/faults'&&request.method==='POST'){const b=await body(request);if(!b.bike_id||!b.description?.trim())return err('Selecione a bicicleta e descreva a avaria.');const rows=await db(ctx,'rpc/create_fault',{method:'POST',body:JSON.stringify({p_bike_id:b.bike_id,p_origin:'comunicada diretamente',p_category:b.category,p_description:b.description,p_severity:b.severity,p_usable:!!b.usable,p_user_id:ctx.user.id})});return json(rows,201)}
  if(parts[0]==='faults'&&parts[1]&&request.method==='PATCH'){const b=await body(request);const result=await db(ctx,'rpc/update_fault',{method:'POST',body:JSON.stringify({p_fault_id:parts[1],p_status:b.status,p_final_bike_status:b.final_bike_status||null,p_user_id:ctx.user.id,p_note:b.note||null})});if(String(b.note||'').trim())await db(ctx,'maintenance_interventions',{method:'POST',body:JSON.stringify({fault_id:parts[1],description:String(b.note).trim(),created_by:ctx.user.id})});return json(result)}
  if(route==='/users'&&request.method==='GET'){if(!allow(ctx,'admin'))return err('Acesso reservado a administradores.',403);const [users,kiosks]=await Promise.all([db(ctx,'users?select=id,full_name,username,role,usual_kiosk_id,active,last_login_at,created_at&order=full_name'),db(ctx,'kiosks?active=eq.true&allows_rentals=eq.true&select=*')]);return json({users,kiosks})}
  if(route==='/users'&&request.method==='POST'){if(!allow(ctx,'admin'))return err('Acesso reservado a administradores.',403);const b=await body(request);if(!b.full_name||!b.username||String(b.password||'').length<6)return err('Preencha os dados e use uma palavra-passe com pelo menos 6 caracteres.');const rows=await db(ctx,'users',{method:'POST',body:JSON.stringify({full_name:b.full_name,username:String(b.username).toLowerCase(),password_hash:await passwordHash(b.password),role:b.role==='admin'?'admin':'funcionario',usual_kiosk_id:b.usual_kiosk_id||null})});await audit(ctx,'criar','utilizador',rows[0].id,null,cleanUser(rows[0]));return json(cleanUser(rows[0]),201)}
  if(parts[0]==='users'&&parts[1]&&parts.length===2&&request.method==='PATCH'){if(!allow(ctx,'admin'))return err('Acesso reservado a administradores.',403);const old=(await db(ctx,`users?id=eq.${parts[1]}&select=*`))[0],b=await body(request);const allowed=['full_name','role','usual_kiosk_id','active'];const update=Object.fromEntries(Object.entries(b).filter(([k])=>allowed.includes(k)));const rows=await db(ctx,`users?id=eq.${parts[1]}`,{method:'PATCH',body:JSON.stringify(update)});await audit(ctx,'alterar','utilizador',parts[1],cleanUser(old),cleanUser(rows[0]));return json(cleanUser(rows[0]))}
  if(parts[0]==='users'&&parts[2]==='password'&&request.method==='POST'){if(!allow(ctx,'admin'))return err('Acesso reservado a administradores.',403);const b=await body(request);if(String(b.password||'').length<6)return err('A palavra-passe deve ter pelo menos 6 caracteres.');await db(ctx,`users?id=eq.${parts[1]}`,{method:'PATCH',body:JSON.stringify({password_hash:await passwordHash(b.password)})});await db(ctx,`sessions?user_id=eq.${parts[1]}`,{method:'PATCH',body:JSON.stringify({revoked_at:new Date().toISOString()})});await audit(ctx,'redefinir palavra-passe','utilizador',parts[1]);return json({ok:true})}
  return err('Página ou operação não encontrada.',404);
 }catch(e){console.error(e);const m=String((e as Error).message);if(e instanceof DbError){if(e.code==='missing_url')return err('Falta configurar SUPABASE_URL no Cloudflare e voltar a publicar.',500);if(e.code==='missing_key')return err('Falta configurar a chave secreta do Supabase no Cloudflare e voltar a publicar.',500);if(e.status===401||e.status===403)return err(`O Supabase recusou a chave configurada (erro ${e.status}). Confirme a chave service_role e volte a publicar.`,500);if(e.status===404||e.code==='PGRST205')return err(`A base de dados não encontrou uma tabela necessária (${e.code}). Confirme se executou integralmente o ficheiro 001_initial.sql e se o esquema public está exposto.`,500);if(e.code==='23505')return err('Já existe um registo com estes dados.',409);return err(`Erro de base de dados: código ${e.code}, estado ${e.status}.`,500)}if(m.includes('bike_not_available'))return err('Uma das bicicletas já não está disponível. Atualize a página.',409);if(m.includes('duplicate')||m.includes('23505'))return err('Já existe um registo com estes dados.',409);const name=e instanceof Error?e.name:'Erro desconhecido';return err(`Erro interno ${name}: ${m.slice(0,180)}`,500)}
};
